- name: Deploy to EC2
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    EC2_USER: ${{ secrets.EC2_USER }}
    EC2_HOST: ${{ secrets.EC2_HOST }}
    EC2_PATH: ${{ secrets.EC2_PATH }}
  run: |
    echo "Starting deployment..."

    # Add SSH key to the agent
    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    # Deploy to EC2
    ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
      echo 'Connected.'
      cd $EC2_PATH
      
      echo 'Updating codebase...'
      git pull origin main
      
      echo 'Installing dependencies...'
      npm install --production

      echo 'Restarting Strapi...'
      pm2 restart strapi --update-env || pm2 start npm --name 'strapi' -- run start

      echo 'Deployment complete.'
    "
